site_name: Tech Insights
site_url: https://blog.alexis-carbillet.com/

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
    - blog
    - navigation.indexes

plugins:
  - search
  - minify:
      minify_html: true
  - blog:
      blog_dir: .
      post_dir: posts
      pagination_per_page: 5
      authors_file: "{blog}/.authors.yml" # Forces it to find your author file

nav:
  - Home: index.md
  - Blog: blog/index.md